spring:
  application:
    name: LibreBlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.24.32.149:3307/libre_blog
    username: fansuregrin
    password: Fg12345#
  data:
    redis:
      host: 172.24.32.149
      port: 6379
      database: 0
      password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
token:
  header: "Authorization"
  expire-time: 1800000 # 过期时间，单位为毫秒
  secret: 7c8c525f-68f8-4647-894c-35daabe3f00b
oss:
  aliyun:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: libreblog
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}